# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Querylet-Output-Excel-OLE
version:      0.13
version_from: lib/Querylet/Output/Excel/OLE.pm
installdirs:  site
requires:
    Querylet:                      0.28
    Test::More:                    0
    Win32::OLE:                    0.17

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
