--- #YAML:1.0
name:                Querylet-Output-Excel-OLE
version:             0.141
abstract:            output query results to Excel via OLE
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Querylet:                      0.3
    Test::More:                    0
    Win32::OLE:                    0.17
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Ricardo Signes <rjbs@cpan.org>
